server:
  port: 8082
  servlet:
    context-path: "/api/v1"


spring:
  datasource:
    url: "jdbc:postgresql://${HOST:walletdb}:5432/wallet_api_dev"
    password: "${POSTGRES_PASS:admin}"
    username: "${POSTGRES_USER:admin}"
    driver-class-name: "org.postgresql.Driver"
    platform: "postgres"
  jpa:
    show-sql: true
    database: "POSTGRESQL"
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: "/swagger/swagger-ui-custom.html"
logging:
  level:
    com:
      internship:
        wallet-api:
          testloglevel:  DEBUG