server:
  port: 8082
  servlet:
    context-path: "/api/v1"
spring:
  datasource:
    url: "jdbc:h2:mem:walletdb"
    password: "wallet"
    username: "wallet"
    driver-class-name: "org.h2.Driver"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: "/swagger/swagger-ui-custom.html"